import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";

const root = join(import.meta.dir, "..");
const output = join(root, ".ai-context.md");
const project = await readFile(join(root, "ai", "project.json"), "utf8");
const packageJson = JSON.parse(await readFile(join(root, "package.json"), "utf8"));

async function listDirectories(path: string): Promise<string[]> {
  const entries = await readdir(path, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
}

const modules = await listDirectories(join(root, "apps", "api", "src", "modules"));
const adrs = (await readdir(join(root, "docs", "adr")))
  .filter((name) => name.endsWith(".md"))
  .sort();
const envExample = await readFile(join(root, "apps", "api", ".env.example"), "utf8");
const envNames = envExample
  .split("\n")
  .map((line) => line.trim())
  .filter((line) => line && !line.startsWith("#") && line.includes("="))
  .map((line) => line.split("=", 1)[0]);

const rootCommands = Object.entries(packageJson.scripts)
  .map(([name, command]) => `- \`${name}\`: \`${command}\``)
  .join("\n");

const content = `# Generated AI context

> Generated by \`bun run context\`. Do not edit manually.

## Project configuration

\`\`\`json
${project.trim()}
\`\`\`

## API modules

${modules.map((name) => `- ${name}`).join("\n")}

## ADRs

${adrs.map((name) => `- docs/adr/${name}`).join("\n")}

## Environment variable names

${envNames.map((name) => `- ${name}`).join("\n")}

## Root commands

${rootCommands}
`;

await writeFile(output, content);
console.log(`Generated ${relative(root, output)}`);
